#! /usr/bin/env python
import argparse


def convert_alpha(number):
    replacements = {
        'A':'2',
        'B':'2',
        'C':'2',
        'D':'3',
        'E':'3',
        'F':'3',
        'G':'4',
        'H':'4',
        'I':'4',
        'J':'5',
        'K':'5',
        'L':'5',
        'M':'6',
        'N':'6',
        'O':'6',
        'P':'7',
        'Q':'7',
        'R':'7',
        'S':'7',
        'T':'8',
        'U':'8',
        'V':'8',
        'W':'9',
        'X':'9',
        'Y':'9',
        'Z':'9'
    }

    return ''.join([replacements[i.upper()] \
        if i.upper() in replacements else i for i in number])


parser = argparse.ArgumentParser(description="Convert a string to numbers")
parser.add_argument("input_str", type=str, help="Input string")
args = parser.parse_args()
print convert_alpha(args.input_str)



